image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew


build_script:
<<<<<<< HEAD
  - ./gradlew test --info -Dselenide.headless=true
=======
  - ./gradlew test --info -Dselenide.headless=true
>>>>>>> f0bccbbb9bef397b069cb48ac8512b636f445a79
